### This file is autogenerated by make_passwdless.py ###

#!/bin/sh

set -o errexit
set -o nounset

mkdir -p ~/.ssh
if [ ! -f ~/.ssh/id_rsa ]; then
    ssh-keygen -q -N '' -t rsa -f ~/.ssh/id_rsa
fi

sshpass -p Hackathon@2022 ssh-copy-id -o StrictHostKeyChecking=no ubuntu@10.206.186.18
sshpass -p Hackathon@2022 ssh-copy-id -o StrictHostKeyChecking=no ubuntu@10.206.186.192
sshpass -p Hackathon@2022 ssh-copy-id -o StrictHostKeyChecking=no ubuntu@10.206.186.5
