FROM python:3.8-slim
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN cp /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && \
echo "Asia/Kolkata" >  /etc/timezone
ADD monitor_log_aggregator monitor_log_aggregator
CMD ["python", "-m","monitor_log_aggregator"]